import prisma from "../config/prisma.config";

async function feedSkills() {
  const skills = [
    { name: "JavaScript" },
    { name: "TypeScript" },
    { name: "Python" },
    { name: "Java" },
    { name: "C" },
    { name: "C++" },
    { name: "C#" },
    { name: "Go" },
    { name: "Rust" },
    { name: "Swift" },
    { name: "Kotlin" },
    { name: "PHP" },
    { name: "Dart" },
    { name: "Perl" },
    { name: "Scala" },
    { name: "Haskell" },
    { name: "Lua" },
    { name: "Objective-C" },
    { name: "R" },
    { name: "F#" },
    { name: "Elixir" },
    { name: "Erlang" },
    { name: "Shell Scripting" },
    { name: "PowerShell" },
    { name: "Groovy" },
    { name: "Bash" },
    { name: "MATLAB" },
    { name: "Julia" },
    { name: "COBOL" },
    { name: "Fortran" },

    { name: "HTML" },
    { name: "CSS" },
    { name: "SASS" },
    { name: "LESS" },
    { name: "Tailwind CSS" },
    { name: "Bootstrap" },
    { name: "Material UI" },
    { name: "React" },
    { name: "Next.js" },
    { name: "Vue.js" },
    { name: "Nuxt.js" },
    { name: "Angular" },
    { name: "Svelte" },
    { name: "Solid.js" },
    { name: "Alpine.js" },
    { name: "Node.js" },
    { name: "Express.js" },
    { name: "NestJS" },
    { name: "Fastify" },
    { name: "Django" },
    { name: "Flask" },
    { name: "Spring Boot" },
    { name: "ASP.NET" },
    { name: "Ruby on Rails" },
    { name: "Laravel" },
    { name: "Symfony" },
    { name: "CodeIgniter" },
    { name: "FastAPI" },
    { name: "Hugo" },
    { name: "Jekyll" },

    { name: "MongoDB" },
    { name: "PostgreSQL" },
    { name: "MySQL" },
    { name: "SQLite" },
    { name: "MariaDB" },
    { name: "Redis" },
    { name: "Cassandra" },
    { name: "Firebase" },
    { name: "Supabase" },
    { name: "AWS DynamoDB" },
    { name: "Google Firestore" },
    { name: "CockroachDB" },
    { name: "DuckDB" },
    { name: "GraphQL" },
    { name: "Prisma" },
    { name: "TypeORM" },
    { name: "Sequelize" },
    { name: "Drizzle ORM" },
    { name: "Neo4j" },
    { name: "CouchDB" },
    { name: "Amazon RDS" },
    { name: "BigQuery" },
    { name: "Snowflake" },
    { name: "Apache Hive" },
    { name: "TimescaleDB" },

    { name: "Docker" },
    { name: "Kubernetes" },
    { name: "Terraform" },
    { name: "Ansible" },
    { name: "Puppet" },
    { name: "Chef" },
    { name: "CI/CD" },
    { name: "GitHub Actions" },
    { name: "Jenkins" },
    { name: "Travis CI" },
    { name: "CircleCI" },
    { name: "ArgoCD" },
    { name: "AWS" },
    { name: "Azure" },
    { name: "Google Cloud" },
    { name: "Cloudflare Workers" },
    { name: "DigitalOcean" },
    { name: "Vercel" },
    { name: "Netlify" },
    { name: "Heroku" },
    { name: "Firebase Hosting" },
    { name: "NGINX" },
    { name: "Apache HTTP Server" },
    { name: "Load Balancing" },
    { name: "Site Reliability Engineering (SRE)" },
    { name: "Cloud Security" },
    { name: "Serverless Computing" },
    { name: "Observability" },
    { name: "Logging & Monitoring" },
    { name: "Grafana" },

    { name: "Ethical Hacking" },
    { name: "OWASP" },
    { name: "Penetration Testing" },
    { name: "Metasploit" },
    { name: "Burp Suite" },
    { name: "Wireshark" },
    { name: "Cloud Security" },
    { name: "Zero Trust Security" },
    { name: "SOC 2 Compliance" },
    { name: "Reverse Engineering" },
    { name: "Malware Analysis" },
    { name: "Exploit Development" },
    { name: "Cryptography" },
    { name: "Blockchain Security" },
    { name: "Bug Bounty" },
    { name: "Forensics" },
    { name: "Security Information & Event Management (SIEM)" },
    { name: "Threat Intelligence" },
    { name: "Risk Assessment" },
    { name: "Cybersecurity Compliance" },
    { name: "Incident Response" },

    { name: "TensorFlow" },
    { name: "PyTorch" },
    { name: "Scikit-learn" },
    { name: "Pandas" },
    { name: "NumPy" },
    { name: "Matplotlib" },
    { name: "Seaborn" },
    { name: "OpenCV" },
    { name: "NLTK" },
    { name: "Hugging Face Transformers" },
    { name: "LangChain" },
    { name: "OpenAI API" },
    { name: "Google Gemini API" },
    { name: "AutoGPT" },
    { name: "AI Model Training" },
    { name: "Fine-Tuning Models" },
    { name: "AI Ethics" },
    { name: "Deep Learning" },
    { name: "Reinforcement Learning" },
    { name: "Computer Vision" },

    { name: "Solidity" },
    { name: "Ethereum" },
    { name: "Smart Contracts" },
    { name: "Web3.js" },
    { name: "Ethers.js" },
    { name: "Cryptography" },
    { name: "Zero-Knowledge Proofs" },
    { name: "zk-SNARKs" },
    { name: "IPFS" },
    { name: "Decentralized Applications (dApps)" },

    { name: "Unity" },
    { name: "Unreal Engine" },
    { name: "Godot" },
    { name: "Three.js" },
    { name: "Babylon.js" },
    { name: "WebGL" },
    { name: "C# for Unity" },
    { name: "Blueprint Scripting" },
    { name: "Shader Programming" },
    { name: "Augmented Reality (AR)" },
    { name: "Virtual Reality (VR)" },

    { name: "Business Strategy" },
    { name: "Project Management" },
    { name: "Product Management" },
    { name: "Lean Startup" },
    { name: "Scrum" },
    { name: "Agile" },
    { name: "Marketing Strategies" },
    { name: "Digital Marketing" },
    { name: "SEO Optimization" },
    { name: "Google Analytics" },

    { name: "Communication Skills" },
    { name: "Leadership" },
    { name: "Teamwork" },
    { name: "Critical Thinking" },
    { name: "Problem-Solving" },
    { name: "Time Management" },
  ];

  await prisma.skill.createMany({
    data: skills,
    skipDuplicates: true, // Avoid duplicate insertion errors
  });

  console.log("Skills added successfully!");
}

export { feedSkills };
